print("Welcome to the Band Name Generator")
city_name = input("What's name of the city you grew up in?\n")
pet_name = input("What's name of your pet?\n")
print("You grew up in " + city_name + " and your pet name is " + pet_name)
print("Your band name could be " + city_name + " " + pet_name)
